apiVersion: v1
kind: Pod

metadata:
   name: webapp-color
   labels:
     app: webapp-color

spec:
    containers:
      - name: webapp-color
        image: webapp-color

        envFrom:
          - configMapRef:
              name: app-config