apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: new-replica-set
  labels:
    app: busybox
    type: busybox-pod

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: busybox
        type: busybox-pod

    spec:
      containers:
        - name: busybox
          image: busybox
  replicas: 4
  selector:
    matchLabels:
      type: busybox-pod